FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# 替换为清华源，加速安装并提高成功率
RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        ffmpeg \
        espeak-ng \
        libespeak-ng1 \
        libespeak-dev \
        libsndfile1 \
        git \
        build-essential \
        python3-dev \
        libffi-dev \
        libssl-dev \
    --fix-missing && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 设置 pip 源
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# 先装 numpy
RUN pip install --no-cache-dir numpy

# 再装 aeneas（如果一定要 pip 安装）
RUN pip install --no-cache-dir aeneas==1.7.3.0

# 然后再安装其他依赖
COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
RUN #pip install --no-cache-dir -r requirements.txt --verbose

# 下载 nltk 数据
RUN python -m nltk.downloader punkt

# 复制应用代码
COPY ./app /app

EXPOSE 8080

CMD ["python", "/app/app.py"]