FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
        curl \
        espeak-ng \
        libespeak-ng1 \
        libespeak-dev \
        libsndfile1 \
        git \
        build-essential \
        python3-dev \
        libffi-dev \
        libssl-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 下载并替换 ffmpeg 为新版
RUN curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz && \
    tar -xJf ffmpeg.tar.xz && \
    cp ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/ && \
    cp ffmpeg-*-amd64-static/ffprobe /usr/local/bin/ && \
    rm -rf ffmpeg.tar.xz ffmpeg-*-amd64-static

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip install numpy

COPY ./app/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt

COPY ./app /app

EXPOSE 8080

CMD ["python", "/app/app.py"]